name: lab 1
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: print-greeting
        run: echo "test run"
      - name: print-goodbye
        run: echo "test run 2"
